# Docker Compose override for development
# Run with: docker compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-development-key-only
    volumes:
      - .:/app
      - /app/venv  # Exclude venv from mounting
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  # Remove nginx for development
  nginx:
    profiles: ["production"]
