services:
  db:
    image: postgres:15
    container_name: ecommerce_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
